MyHELLOWEENCARD
hackclub/OnBoard pull request #1239
Opened 2024-10-20 17:03 UTC by ristonrodrigues723

## Submission Checklist:

- [ X] I am a current high school, middle school, or home schooled student.
  - [ X] I am 18 or under
  - [X ] I have filled out the [verification form](https://verify.onboard.hackclub.com) **(do this for every pull request)**
    -  *or the [legacy verification form](https://legacy.verify.onboard.hackclub.com) if the above doesn't work* 
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [ X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [ X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [ X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [ X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [ X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ X] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ X] (Optional) This project is for [Trick or Trace](https://showcase.hackclub.com/)[^3].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!
[^3]: [Trick or Trace](https://trickortrace.hackclub.com/) is a limited time design contest for PCBs, enter your PCB into one of the three catagories and by peer voting, get chosen for a 100$ additional grant from OnBoard.

2024-10-20 17:03 UTC, prophetorpheus commented
<!-- MY-ONBOARD-BOT --> Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/Riston_buinesscard:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

2024-10-22 18:12 UTC, blazecoding2009 requested changes
Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of the cart ordering process instead of completing the checkout process.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.

Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!

2024-10-26 07:16 UTC, ristonrodrigues723 commented
> Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of the cart ordering process instead of completing the checkout process. For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:
> 
> 1. Click "Secure Checkout": After adding your PCB to the cart
> 2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
> 3. Close that tab and open a new one to jlcpcb.com, then click "Order History" and take a screenshot. It should show all the details of your order.
> 
> Please take a screenshot of your unpaid order instead of a picture of your cart, and upload it as cart.png. This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congrats on making the PCB!

hey blaze it seems to not let me submit order without adding payment order i tried it multiple times but the same

2024-10-26 07:17 UTC, ristonrodrigues723 commented
projects/Riston_buinesscard/cart (2).png 
it asks for payment to proceed further

2025-01-02 18:46 UTC, LimesKey commented
> hey blaze it seems to not let me submit order without adding payment order i tried it multiple times but the same
You need to go to your JLCPCB past orders now, and the order should be there

2025-01-02 18:47 UTC, LimesKey commented
Can you reupload your schematic from the schematic tab on EasyEDA?

2025-01-03 11:55 UTC, ristonrodrigues723 commented
> Can you reupload your schematic from the schematic tab on EasyEDA?

hey just did that [Schematic_MyBusinessCard_2025-01-03.pdf](https://github.com/ristonrodrigues723/OnBoard/blob/main/projects/Riston_buinesscard/Schematic_MyBusinessCard_2025-01-03.pdf) is added can u recheck

2025-01-03 11:56 UTC, ristonrodrigues723 commented
@LimesKey ,ryan pls check just added the right schemetic

2025-01-04 06:56 UTC, LimesKey commented
Sorry, I can't accept the hackercard as a Trick or Trace submission, do you have another board?

2025-01-04 07:58 UTC, ristonrodrigues723 commented
> Sorry, I can't accept the hackercard as a Trick or Trace submission, do you have another board?

currently not,
what kind needs to be designed

2025-01-04 08:13 UTC, LimesKey commented
Would you not like to do Trick or Trace and just use your regular OnBoard grant?

2025-01-04 08:24 UTC, ristonrodrigues723 commented
> Would you not like to do Trick or Trace and just use your regular OnBoard grant?

actually i would like to do it i thought adding some spooky images on the pcb and   directing ppl to my boba manor site that is halloween themed would have suffcied. should i design a new pcb for this? , i wanted to do an led matrix to display images but dont have an idea if it would work here

2025-01-04 18:36 UTC, ristonrodrigues723 commented
hey i found a board i would like to design or trice or trace isn designing a snowflake led pcb 
allowed?

2025-01-04 22:37 UTC, LimesKey commented
do that for Hacky Holidays not Trick or Trace...

2025-01-06 14:07 UTC, ristonrodrigues723 commented
pumpkin shaped mini spookey badges with cel holder led blinking and 555 Timer IC and cell holder should it suffice?

2025-01-06 14:23 UTC, ristonrodrigues723 commented
can add esp to it but dont know if it will work

2025-01-07 17:32 UTC, ristonrodrigues723 commented
![Schematic_skull1_2025-01-07](https://github.com/user-attachments/assets/ca5bb244-c71c-4e2b-8343-d0a55ae6c4ae)
this

2025-01-07 21:39 UTC, LimesKey commented
That looks nice! Also, is that a 1000uF capacitor, why do you need a 1000uF capacitor?

2025-01-08 04:23 UTC, ristonrodrigues723 commented
> That looks nice! Also, is that a 1000uF capacitor, why do you need a 1000uF capacitor? See if you can work on the PCB now

i gave the plan to chat gpt and clude multiple tiles for clarifications they insisted on it being used like i want to connect these it suggested using the capacitor should the save the neopixels fromm flucations. ill start working on it

2025-01-08 04:25 UTC, ristonrodrigues723 commented
i know the 1000uf capacitor doesnt make sense as outut will be from xaio ill no idea why both ai suggested using it

2025-01-08 08:59 UTC, ristonrodrigues723 commented
![image](https://github.com/user-attachments/assets/c1d9876a-efcf-44c3-b513-6de33c24e937)
wiating to cut it in form of the skull finding  good img for it

2025-01-08 09:17 UTC, ristonrodrigues723 commented
![image](https://github.com/user-attachments/assets/a89dbaae-3883-4e53-8bcb-d0845d644b5b)

2025-01-08 09:17 UTC, ristonrodrigues723 commented
now adding img cuting uumg based outline

2025-01-08 10:35 UTC, ristonrodrigues723 commented
![image](https://github.com/user-attachments/assets/a98e67ec-c937-4d9a-8bdc-7075973d5c8c)
changed the capacitor to 470uf and this

2025-01-08 10:36 UTC, ristonrodrigues723 commented
is it ok?

2025-01-10 00:27 UTC, LimesKey commented
Can you upload the files to this pull request?

2025-01-10 04:30 UTC, ristonrodrigues723 commented
yep doing

2025-01-11 23:38 UTC, LimesKey requested changes
it looks like you took a picture of your order details rather than the completed unpaid order.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to the [JLCPCB Order page](https://jlcpcb.com/user-center/orders/), then take a rectangular screenshot of the PCB you just submitted. It should show all the details of your order including the price and assembly.

This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congratulations on making the PCB! Please ask in [#electronics](https://slack.com/archives/C056AMWSFKJ) in the [Slack](https://hackclub.com/slack/) if you need any further help.

2025-01-13 10:36 UTC, LimesKey commented
Thanks for submitting your PCB to Trick or Trace, and although Trick or Trace has, unfortunately, ended on Oct 21st, <ins>we are still giving out a limited number of grants</ins>. We'll let you know if your project gets chosen. In the meantime, we're **sending you a small electronics kit** to congratulate your accomplishment in making this PCB.

2025-01-13 10:36 UTC, merged

2025-01-13 16:50 UTC, ristonrodrigues723 commented
thanks a lot