(Hacky Holidays) Gift Tag
hackclub/OnBoard pull request #1364
Opened 2024-12-22 00:01 UTC by udu3324

## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://verify.onboard.hackclub.com) **(do this for every pull request)**
    -  *or the [legacy verification form](https://legacy.verify.onboard.hackclub.com) if the above doesn't work* 
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [ ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!
[^3]: [Trick or Trace](https://trickortrace.hackclub.com/) is a limited time design contest for PCBs, enter your PCB into one of the three catagories and by peer voting, get chosen for a 100$ additional grant from OnBoard.

This is for Hacky Holidays. Here's it working in [wokwi](https://wokwi.com/projects/417564934930792449)!

2024-12-22 00:03 UTC, prophetorpheus commented
<!-- MY-ONBOARD-BOT --> Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/gift_tag:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png | ![cart.png](<https://raw.githubusercontent.com/hackclub/OnBoard/515a2a86ca2d35318a0cd07180b63f3393cbd53d/projects/gift_tag/cart.png>) |
|✅| gerber.zip | |
|❌ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/515a2a86ca2d35318a0cd07180b63f3393cbd53d/projects/gift_tag/schematic.pdf>) | You must export your schematic file as schematic.pdf |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/515a2a86ca2d35318a0cd07180b63f3393cbd53d/projects/gift_tag/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

2025-01-01 19:55 UTC, udu3324 commented
bump

2025-01-09 14:09 UTC, udu3324 commented
bump

2025-01-13 10:48 UTC, LimesKey requested changes
Hi @udu3324, thanks for your Hacky Holidays Submission, just before we review your pull request, we need to ask you a few preliminary questions.

1. Does your PCB require a battery, either a LIR2032 or a CR2032?
2. Is your PCB complex (parts-wise) and or requires Standard Assembly?
3. About how long have you been working with electronics or PCB design?

Lastly, if you haven't done it already, we'll be needing your position and bill of materials (BOM) files. These files can be found in a `.csv` file format and should be in your `/src` directory with them named appropriately. Also, please be sure you've supplied all your `JLCPCB Part` or `LCSC Part` numbers, if you need help, please let me know or message in [#hacky-holidays](https://hackclub.slack.com/archives/C083SK3G5D3).

2025-01-14 05:47 UTC, udu3324 commented
1, It needs two CR2032 batteries to function
2, It only needs economic assembly but has three extended parts from lcsc. It doesn't include the two battery holders/xiao esp32c3 to save on handling fees (i need to buy them separately to solder)
3, I have been doing pcb design for about half a year and still learning!

I have added the bom from jlcpcb with all the parts selected for assembly and the bom/placement files from kicad.

2025-01-23 20:44 UTC, LimesKey commented
Hey, sorry for the delay in reviewing, but we're all ready to get your shipping out finally. One minor thing, are you able to use this specific CR2032 holder as we already have it in stock?
[CR2032-Holder.kicad_mod.zip](https://github.com/user-attachments/files/18526726/CR2032-Holder.kicad_mod.zip)

2025-01-23 21:37 UTC, udu3324 commented
> Hey, sorry for the delay in reviewing, but we're all ready to get your shipping out finally. One minor thing, are you able to use this specific CR2032 holder as we already have it in stock? [CR2032-Holder.kicad_mod.zip](https://github.com/user-attachments/files/18526726/CR2032-Holder.kicad_mod.zip)

Just checked the footprint, and it sadly looks like they both differ too much to be able to swap out for another it. I can go ahead with swapping them out if the pcb isn't manufactured yet

![{9A971789-2552-4BF0-99A3-7A2D3B157DBB}](https://github.com/user-attachments/assets/18899ff0-73f5-4f3a-88b0-413cfed4cdc6)
(top is yours, bottom is current one)

2025-01-26 03:35 UTC, Scott170c commented
We are currently having a problem with sourcing the neopixels, so you will have some time to change the footprint out while we resolve the issue. Other than that great submission, looks awesome!

2025-01-27 14:35 UTC, udu3324 commented
> It's time, last questions: Did you change the battery holder? Also can you solder the MCU yourself (have a soldering iron) or would you prefer if we did it for you instead?

I have changed to the new battery holder but had to use standard assembly because of the leds sadly. I can also solder the MCU

Here's the new cost 
![Screenshot_20250127-083226.png](https://github.com/user-attachments/assets/2ef196cf-adf3-472c-94fa-192aa2063b5e)

2025-01-27 18:19 UTC, snaeker58 commented
Hi Danny!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/NJIWxo). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the [#electronics](https://slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/) once you get it! Please don't hesitate to reach out if you have any questions!

2025-01-27 18:20 UTC, merged

2025-01-27 20:46 UTC, udu3324 commented
@snaeker58 I have a slight problem. JLCPCB forgot to calculate sales tax for some reason 💀 

![Screenshot_20250127-144344.png](https://github.com/user-attachments/assets/e6d31f0f-ef7b-4aac-b224-8d96c6cc43ff)

2025-01-28 07:20 UTC, snaeker58 commented
There I just granted you the 5.71$, please try avoiding this in the future!