Create README.md
hackclub/OnBoard pull request #1365
Opened 2024-12-22 01:25 UTC by rivques

## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://verify.onboard.hackclub.com) **(do this for every pull request)**
    -  *or the [legacy verification form](https://legacy.verify.onboard.hackclub.com) if the above doesn't work* 
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [X] Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [N/A] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

**SUBMITTER'S NOTE: THIS IS A #hacky-holidays PROJECT.** I'm not totally clear on how its requirements differ from standard OnBoard, but I'm happy to make any changes you'd like to see made :)

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!
[^3]: [Trick or Trace](https://trickortrace.hackclub.com/) is a limited time design contest for PCBs, enter your PCB into one of the three catagories and by peer voting, get chosen for a 100$ additional grant from OnBoard.

2024-12-22 01:26 UTC, prophetorpheus commented
<!-- MY-ONBOARD-BOT --> Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/fire_decoration:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png | ![cart.png](<https://raw.githubusercontent.com/hackclub/OnBoard/745401634e09d5d6b5979305d287591416238402/projects/fire_decoration/cart.png>) |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/745401634e09d5d6b5979305d287591416238402/projects/fire_decoration/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/745401634e09d5d6b5979305d287591416238402/projects/fire_decoration/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/745401634e09d5d6b5979305d287591416238402/projects/fire_decoration/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

2025-01-11 04:02 UTC, rivques commented
oh also i made a [simulator](https://github.com/rivques/flame_decoration_sim) so i could write the flame patterns before i got the board
behold a gif
![flame-sim-demo](https://github.com/user-attachments/assets/bc21c385-efc3-4c6f-8f18-94a92d03fc61)

2025-01-11 23:48 UTC, LimesKey commented
very cool, do you want to share this in #hacky-holidays or #electronics on the slack?

2025-01-13 10:48 UTC, LimesKey requested changes
Hi @rivques, thanks for your Hacky Holidays Submission, just before we review your pull request, we need to ask you a few preliminary questions.

1. Does your PCB require a battery, either a LIR2032 or a CR2032?
2. Is your PCB complex (parts-wise) and or requires Standard Assembly?
3. About how long have you been working with electronics or PCB design?

Lastly, if you haven't done it already, we'll be needing your position and bill of materials (BOM) files. These files can be found in a `.csv` file format and should be in your `/src` directory with them named appropriately. Also, please be sure you've supplied all your `JLCPCB Part` or `LCSC Part` numbers, if you need help, please let me know or message in [#hacky-holidays](https://hackclub.slack.com/archives/C083SK3G5D3).

2025-01-13 12:36 UTC, rivques commented
1. No
2. No
3. I've been working with electronics for 8ish years, and designing PCBs for a little over a year

I just pushed a commit with the production files.

2025-01-26 03:37 UTC, Scott170c commented
Sorry about the wait, your PR looks awesome! You should be ready to get your grant, we are just sorting a few things out with the neopixels! I will get someone to mark this PR as stalled so we know to come back to it when we resolve the neopixel issue :)

2025-01-27 13:58 UTC, snaeker58 requested changes
Hi River, do you want to solder the XIAO Esp32c3 yourself (do you have an iron) or would you prefer for us to solder it for you?

2025-01-27 14:01 UTC, rivques commented
I can solder it myself

2025-01-27 14:04 UTC, snaeker58 requested changes
Before giving you your grant lemme slap this in your face:
Hi River, 

Thanks for submitting your PCB pull request for OnBoard! However, it looks like you took a picture of your order details rather than the completed unpaid order.  For us to have the full picture of pricing and the PCB your ordering, please follow the steps in this guide [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md) or here:

1. Click "Secure Checkout": After adding your PCB to the cart
2. Enter your shipping information and add a coupon code if you have one, then click "Submit Order", do not add any payment options
3. Close that tab and open a new one to the [JLCPCB Order page](https://jlcpcb.com/user-center/orders/), then take a rectangular screenshot of the PCB you just submitted. It should show all the details of your order including the price and assembly.

This will allow us to spot any mistakes and give you ways to reduce the cost or customs fee. Congratulations on making the PCB! Please ask in [#electronics](https://slack.com/archives/C056AMWSFKJ) in the [Slack](https://hackclub.com/slack/) if you need any further help.

2025-01-27 23:18 UTC, rivques commented
when reuploading the files to JLC, I got a popup that says that the WS2812Bs are now standard assembly only. [This slack message](https://hackclub.slack.com/archives/C083SK3G5D3/p1737755011968639) says I should wait for further news, is that still true?

2025-01-28 07:21 UTC, snaeker58 commented
> when reuploading the files to JLC, I got a popup that says that the WS2812Bs are now standard assembly only. [This slack message](https://hackclub.slack.com/archives/C083SK3G5D3/p1737755011968639) says I should wait for further news, is that still true?

Nope, we are granting all now with standard assembly!

2025-02-03 21:49 UTC, Pegoku commented
Please use the correct order history screenshot. You have to continue the order process. 
![image](https://github.com/user-attachments/assets/71a3b5fc-26c9-4379-922a-0ad237c098bb)
for the Order History, you have to continue checkout and when asked to pay, just close the page. then you can go to order history and you'll find the PCB order there.

2025-02-03 23:29 UTC, rivques commented
Thanks for the help, that should be fixed now!

2025-02-04 12:23 UTC, Pegoku commented
Hi!

I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/qnZI16). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the [#electronics](https://slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/) once you get it! Please don't hesitate to reach out if you have any questions!

2025-02-04 12:23 UTC, merged