haleysbusinesscard
hackclub/OnBoard pull request #1371
Opened 2024-12-23 09:34 UTC by rhinohaley

## Submission Checklist:

- [X] I am a current high school, middle school, or home schooled student.
  - [X] I am 18 or under
  - [X] I have filled out the [verification form](https://verify.onboard.hackclub.com) **(do this for every pull request)**
    -  *or the [legacy verification form](https://legacy.verify.onboard.hackclub.com) if the above doesn't work* 
- [X] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [X] I made this board from scratch, even if I followed a tutorial
- [X] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [ X Created a folder under `onboard/projects`
  - [X] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [X] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [X] Created a folder called `src` and uploaded design files
  - [X] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [X] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [X] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [X] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for OnBoard Live[^2].
- [ ] (Optional) This project is for Hacky Holidays[^3].
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.
[^2]: OnBoard Live is a special version of OnBoard where you can earn more money for designing advanced boards. Check out the #onboard-live channel on [our Slack](https://hackclub.com/slack/?event=onboard)!
[^3]: [Hacky Holidays](https://hacky-holidays.hackclub.com/) is a limited time PCB event, design a holiday-themed PCB this Winter, and get it shipped.

2024-12-23 09:36 UTC, prophetorpheus commented
<!-- MY-ONBOARD-BOT --> Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/haleysbusinesscard:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png | ![cart.png](<https://raw.githubusercontent.com/hackclub/OnBoard/4075114b024ae6d89e15611c6309b1b32ce849cd/projects/haleysbusinesscard/cart.png>) |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/4075114b024ae6d89e15611c6309b1b32ce849cd/projects/haleysbusinesscard/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/4075114b024ae6d89e15611c6309b1b32ce849cd/projects/haleysbusinesscard/schematic.pdf>) |
|✅| Source files - EasyEDA |  Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/4075114b024ae6d89e15611c6309b1b32ce849cd/projects/haleysbusinesscard/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

2024-12-23 21:12 UTC, LimesKey submitted a review, later dismissed
Hi @rhinohaley!

You have not selected assembly from JLCPCB, so there won't be any components (NFC chip, LEDs, etc) installed on your board. Please check out https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md for how to do this. You can order up to 5 assembled boards.

2024-12-24 08:37 UTC, rhinohaley commented
Hello!

I've selected assembly and changed it. What do I do now?

On Mon, Dec 23, 2024 at 1:13 PM Ryan ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @rhinohaley <https://github.com/rhinohaley>!
>
> You have not selected assembly from JLCPCB, so there won't be any
> components (NFC chip, LEDs, etc) installed on your board. Please check out
> https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md
> for how to do this. You can order up to 5 assembled boards.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/OnBoard/pull/1371#pullrequestreview-2521148465>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BLPNCKPPKOSU4ATWSEFB6TD2HB4GLAVCNFSM6AAAAABUCXN5IOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMRRGE2DQNBWGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-12-24 08:39 UTC, rhinohaley commented
[image: Screenshot 2024-12-24 12.38.34 AM.png]
Here is a screenshot of my new order with assembly this time:

On Mon, Dec 23, 2024 at 1:13 PM Ryan ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @rhinohaley <https://github.com/rhinohaley>!
>
> You have not selected assembly from JLCPCB, so there won't be any
> components (NFC chip, LEDs, etc) installed on your board. Please check out
> https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md
> for how to do this. You can order up to 5 assembled boards.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/OnBoard/pull/1371#pullrequestreview-2521148465>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BLPNCKPPKOSU4ATWSEFB6TD2HB4GLAVCNFSM6AAAAABUCXN5IOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMRRGE2DQNBWGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-12-31 20:17 UTC, WolfGamer2 commented
Heya! I am not able to see the screenshot

2024-12-31 20:18 UTC, WolfGamer2 requested changes
Please upload a new cart.png file!

2024-12-31 20:20 UTC, WolfGamer2 commented
Also make sure to go through the checkout process and send the screenshot of order details :)

2025-01-04 07:02 UTC, WolfGamer2 commented
Lmk when you have it done!

2025-01-10 06:38 UTC, LimesKey requested changes
Your `schematic.pdf` is incorrect and should be the electrical component schematic taken from the schematic tab of EasyEDA not in the PCB tab.

Also, your PCB traces need a lot of fixing, your PCB will not work as is and the traces need to be rerouted. Good luck and let me or @WolfGamer2 if you need help!

2025-02-25 18:31 UTC, maxwofford commented
Hey @rhinohaley, i'm going to close this for now so it doesn't show up in our review list, but if you get it updated or need help with getting it fixed just message in here!

2025-02-25 18:31 UTC, closed without merging