Usb hub
hackclub/OnBoard pull request #228
Opened 2023-10-17 19:45 UTC by krrishvchhabra

## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/shrbcDANe6ug6gj0p)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed [DIRECTIONS.md](https://github.com/hackclub/OnBoard/blob/main/DIRECTIONS.md)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber, sources, and schematic
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

2023-10-17 20:21 UTC, karmanyaahm requested changes
Just like you put in design.json, can you go to the PCB tab on EasyEDA and export a PCB design JSON?
LGTM other than that

2023-10-18 10:03 UTC, krrishvchhabra commented
[PCB_PCB_Krrish's USB HUB_2023-10-18.json](https://github.com/hackclub/OnBoard/files/13006205/PCB_PCB_Krrish.s.USB.HUB_2023-10-18.json)

Added

2023-10-19 07:10 UTC, karmanyaahm approved these changes

2023-10-19 07:13 UTC, karmanyaahm commented
I love that you're making more progress with PCBs! You can go ahead and order the board (should already have grant details from your hacker card), will merge in a bit.

2023-10-25 15:47 UTC, merged