Alexander Lee's Pull Request
hackclub/OnBoard pull request #331
Opened 2024-01-29 03:15 UTC by shadow2418889

## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#onboard`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on Slack
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md`
  - [x] Uploaded Gerber, sources, and schematic
  - [x] Uploaded screenshot of PCB order with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [n/a] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [ ] (Optional) This project is from a tutorial[^1].
- [x] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: 125

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

2024-01-29 03:16 UTC, prophetorpheus commented
<!-- MY-ONBOARD-BOT --> Hi, I'm Orpheus Leap! Here to help you review your PR.

  You can view a render of your board over on [tracespace.io](<https://tracespace.io/view/?boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/d590f2999cb9d0e4a6f096a6c6553586fd91806c/projects/Alexander's ESP32 Omini Directional PCB Robot/Gerber_PCB_Robot Tour 2023 V0.1.zip>)!

  Happy OnBoarding!

2024-01-29 21:27 UTC, karmanyaahm requested changes
LOVE THIS IDEA!!!!

Small blocker, just like your upload your PCB_PCB.json file, please File > Export > EasyEDA a JSON  from the Schematic tab of your project.


This is not a requirement, but there are definitely ways to optimize your design to fit it in <$100; I don't know whether you can achieve that with your competition timeline.

**Cost saving suggestions** (there are more, these are just the few things that stood out to me, ask questions on Slack):
Just a suggestion though, if you replace the ESP32 module with an ESP32-SOLO-1, you might be able to save a lot of money. Right now your ESP32 S2 module is forcing you to use Standard Assembly, which adds like $20 to your assembly cost. I don't know how practical this is in your application, so this is just a suggestion that you may or may not want to take.

Here are also a few notes to get basically free money:
1. These few capacitors are all "Extended parts". This means that it costs $3 extra per part for JLCPCB to grab these.
![image](https://github.com/hackclub/OnBoard/assets/32671690/97cbfed0-0848-4ada-a63a-1cbc46ccc48c) In your schematic, you can replace these with generic capacitors with an equivalent value, and they should work the same. 
![image](https://github.com/hackclub/OnBoard/assets/32671690/f20a8ba9-74e1-4aef-91b4-8cf05d30a09b)
2. Same thing applies to these transistors. 
![image](https://github.com/hackclub/OnBoard/assets/32671690/44d08b70-386f-45e2-8888-23a45fca9db8) You can go to https://jlcpcb.com/parts. Search "transistor", and select the "Basic parts" checkbox.
3. And buttons are the same as transistors
![image](https://github.com/hackclub/OnBoard/assets/32671690/8f8217b2-ee57-4960-abe4-7a00c26d506e)






cc @Hugoyhu review circuit things plz?

2024-02-02 00:44 UTC, sarthaktexas approved these changes
Howdy Alex! I'm approving your student verification :)

2024-02-02 16:50 UTC, karmanyaahm commented
@shadow2418889 lmk if there's any way I can help you get your grant sooner!

2024-02-03 15:57 UTC, Hugoyhu commented
HI! Sorry for the late reply. @shadow2418889 let me know if you'd like a schematic / routing review.

2024-02-03 20:31 UTC, shadow2418889 commented
@Hugoyhu A review would be greatly appreciated! Any tips on how I could improve my design for the future would also be nice. Thank you all, Alexander

2024-02-03 21:36 UTC, Hugoyhu commented
@shadow2418889 can you upload your schematic .json to the /src folder? Thank you

2024-02-03 22:08 UTC, shadow2418889 commented
I uploaded the export from EasyEda. Thank you all again.

2024-02-07 19:01 UTC, Hugoyhu requested changes
Hi all and sorry for the wait. Currently checking your schematic. Few things:

- On U2 (CP2102N-28) why is RXD and TXD swapped? I'm referencing [the Adafruit CP2102N-24 Friend.](https://cdn-learn.adafruit.com/assets/assets/000/111/711/original/adafruit_products_schem.png?1652465596)
- Should VREGIN be connected to 3.3V? [SiLabs datasheet says 3.6-5,25 per fig 2.2](https://www.silabs.com/documents/public/data-sheets/cp2102n-datasheet.pdf)

I will take a look at the other portions of this sch soon, thse two are issues taht pop out to me for the USB-serial portion.

2024-02-08 02:01 UTC, shadow2418889 commented
Hi Hugo,
First of all, thank you for your help and I'm completely fine about the delay.

For RXD and TXD swappage I was just following the schematics the ESPRESSIF M-1 Devkit:
![image](https://github.com/hackclub/OnBoard/assets/35787668/3fd12b95-3421-411d-8116-2b76fb956d0f)
and Feranec's tutorial https://youtu.be/S_p0YV-JlfU?t=2161. Honestly, I have no idea why the inputs are swapped, but I trust the schematic and Feranec. 

The VREGIN connection also comes from the ESPRESSIF M-1 Devkit
![image](https://github.com/hackclub/OnBoard/assets/35787668/1d0080f2-6d61-437a-a7da-c2bdb9ea18e3)
While I am outside the recommended voltage, the datasheet states that the CP2102N can handle an input voltage 3V, so uh, I guess I can pray that it works out fine.

Thanks, Alexander

2024-02-08 19:33 UTC, Hugoyhu commented on projects/Alexander's ESP32 Omini Directional PCB Robot/Schematic_Robot Tour 2023_2024-01-28.pdf
Currently reading the datasheet for TPS62745 [here](https://www.ti.com/lit/ds/symlink/tps62745.pdf?ts=1707383667608&ref_url=https%253A%252F%252Fwww.google.com%252F): it seems your VSEL pins are connected to VOUT and not GND.

There's also a newer part TI recommends with "smaller size, better efficiency" which might be ideal for your battery-powered project: [TPS629203](https://www.ti.com/product/TPS629203)

I'll take a looka t your motor drivers next (nice part selection! Fun coincidence, we were looking at these for our Blot machine). I'll make a comment when I am done checking that part.

For the previous comment RE CP2102N and etc: I have checked against the Espressif schematic and it seems OK. If you followed that then it should be good and I don't immediately see any problems.

2024-02-12 07:20 UTC, karmanyaahm approved these changes
I'm approving this for now. Please look at Hugo's comments to make sure your robot will work. Your grant should be sent soon (ping @sarthaktexas)!

2024-02-12 07:20 UTC, merged

2024-02-13 16:20 UTC, shadow2418889 commented
Thank you all! I finished the changes and I'll talk to Sarthak.

2024-02-13 18:27 UTC, shadow2418889 commented on projects/Alexander's ESP32 Omini Directional PCB Robot/Schematic_Robot Tour 2023_2024-01-28.pdf
I'm looking for an output of 3.3v, so I just followed the recommended schematics:
![image](https://github.com/hackclub/OnBoard/assets/35787668/afbc3eac-c3e7-490d-846b-9692a551a0b8)
JLCPCB doesn't have any TPS629203 in stock unfortunately.

2024-02-14 19:28 UTC, Hugoyhu reviewed
This seems more or less OK for the schematic and well put together. I don't see any issues for DRV8833 against datasheet. Habve you run DRC on your PCB?

2024-02-14 19:30 UTC, Hugoyhu commented
Oh, one note on PCB. Do you paln on using the BT / WiFi for ESP32? If so, the module should be on the edge of the PCB. at the very least, the area under the antenna section should have no copper fill, and at best, there should be a cutout or the antenna on module extends out.

2024-02-15 04:09 UTC, shadow2418889 commented
I was gonna play with Bluetooth control but it wasn't really vital for the project. Thanks for letting me know, ill probably update the design to better support wireless connectivity sometime in the future.