Div's pi-day pcb!
hackclub/OnBoard pull request #679
Opened 2024-06-17 05:30 UTC by Iamdiv7

## Submission Checklist:

- [x] means I understand, and have completed.

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)(i am in the USA)

- [ ] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

2024-06-17 05:31 UTC, prophetorpheus commented
<!-- MY-ONBOARD-BOT --> Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/3_14 Pi-day PCB:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|❌ | cart.png | You need to include a screenshot of your JLCPCB. Check out [these instructions](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md#pcb-review). If you already have one, make sure it's a PNG file named exactly "cart.png". |

**❌❌❌Cannot find a Gerber File. Please export a gerber from your PCB Design software and name it exactly "gerber.zip".**
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

2024-06-17 20:48 UTC, abitchinmorewaysthanone commented
Hi Div,
It seems like your files are organized incorrectly. Please check out the [merged projects](https://github.com/hackclub/OnBoard/tree/main/projects) or review [this section](https://github.com/hackclub/OnBoard?tab=readme-ov-file#5-add-your-design-to-your-project-repo) of the tutorial to see how to organize them correctly.

2024-06-19 06:32 UTC, abitchinmorewaysthanone requested changes
Hi Divya,
Please remove the files that are outside of /3_14 Pi-day PCB/ and place your .JSON files in a folder /3_14 Pi-day PCB/src/.
Thanks!

2024-06-24 10:36 UTC, Iamdiv7 commented
how do you delete a file? Because every time I click the 3 dots to delete it, and click delete, it does nothing. and how do you make a file and add the json files?

2024-06-26 05:44 UTC, torbers requested changes
Hi Div,
Your files are all correct (thank you @LimesKey !) but it seems like you haven't done the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form) - we need this info to contact you and send your grant! Thank you!

2024-06-26 07:13 UTC, Iamdiv7 commented
Thank you for working with me on this so that I can get my pcb, and I have
just submitted the verification form.

On Tue, Jun 25, 2024 at 10:45 PM tori ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi Div,
> Your files are all correct (thank you @LimesKey
> <https://github.com/LimesKey> !) but it seems like you haven't done the verification
> form <https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form> - we
> need this info to contact you and send your grant! Thank you!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/OnBoard/pull/679#pullrequestreview-2140647970>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BDM73XVRLJG4CQ6QHEHEXVTZJJIO5AVCNFSM6AAAAABJNJLNPGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNBQGY2DOOJXGA>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2024-06-26 07:55 UTC, torbers commented
ok, looks great!
I've just sent you your [grant for OnBoard](https://hcb.hackclub.com/grants/woQIj7). You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

2024-06-26 07:55 UTC, torbers approved these changes

2024-06-26 07:55 UTC, merged

2024-06-27 13:45 UTC, Iamdiv7 commented
Hello, I am on the shipping part of getting the pcb, and the price is varying depending on the shipping express I choose. So the price will vary from $54.67 to $62.72. I am still figuring out which one to choose. thanks for acknowledging.

2024-06-27 17:31 UTC, LimesKey commented
Try to choose the cheaper one with the Standard Direct Line, but for next time you should have went through the order process and then have submitted the unpaid but completed order with the shipping already selected, that's ok though.

> Thanks for submitting your PCB order! However, it looks like you took a picture of your cart instead of completing the checkout process. To ensure your order gets processed correctly, please follow these steps:


>1. Click "Secure Checkout": After adding your PCB to the cart, make sure to click "Secure Checkout."
>2. Enter your shipping information: Fill in your shipping details as prompted.
>3. Take a screenshot of your unpaid order: Once you reach the final page before payment, take a screenshot of this page. It should show all the details of your order.


>Please send me a screenshot of your unpaid order instead of a picture of your cart. This will help us review your order more >efficiently. Congrats on making the PCB though!

2024-06-28 04:21 UTC, Iamdiv7 commented
In total, HCB has paid $61.77 for the pcb.