add: phthallo's usb hub
hackclub/OnBoard pull request #689
Opened 2024-06-19 10:43 UTC by phthallo

## Submission Checklist:

- [x] I am a current high school, middle school, or home schooled student.
  - [x] I am 18 or under
  - [x] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [x] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [x] I made this board from scratch, even if I followed a tutorial
- [x] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [x] Created a folder under `onboard/projects`
  - [x] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [x] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [x] Created a folder called `src` and uploaded design files
  - [x] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [x] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [x] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [x] (Optional) This project is from a tutorial[^1].
- [ ] (Optional) This project is for [the Trail](https://trail.hackclub.com/).
- [ ] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

2024-06-19 15:07 UTC, LimesKey requested changes
Hey @phthallo, your board looks great but I'm having trouble viewing your `schematic.pdf`, it seems like that's just a screenshot of the PCB layout rather than the electrical schematic. Take a look at the other pull requests for an example and let me know if you need help.

2024-06-19 22:03 UTC, phthallo commented
should be fixed now, sorry about that !

2024-06-21 18:06 UTC, LimesKey approved these changes

2024-06-21 18:06 UTC, LimesKey commented
Hi @phthallo!
I've just sent you your grant for OnBoard. You should have received an invite in your email. There will be instructions on how to use your debit card attached should you need them. Please remember to upload your receipts when you make purchases.

**Also, unfortunately, we're unable to offer support with reimbursements for customs fees, including reimbursements using leftover grant funds. Please [keep this in mind](https://jlcpcb.com/help/article/18-Customs,-Duties-and-Taxes) before you make any purchases.** More info in the OnBoard [community shipping doc](https://github.com/hackclub/OnBoard/blob/main/community/shipping.md).

I'm looking forward to seeing your PCB be manufactured! Send pictures in the #electronics channel on Slack once you get it! Please don't hesitate to reach out if you have any questions!

2024-06-21 18:07 UTC, merged

2024-06-21 23:48 UTC, phthallo commented
awesome, thank you!