MelonMars OnBoard
hackclub/OnBoard pull request #860
Opened 2024-07-22 20:47 UTC by MelonMars

## Submission Checklist:

- [✅ ] I am a current high school, middle school, or home schooled student.
  - [ ✅] I am 18 or under
  - [ ✅] I have filled out the [verification form](https://airtable.com/app4Bs8Tjwvk5qcD4/pagxECjJZOgvKVnLd/form)
- [✅ ] I have joined the [`#electronics`](https://hackclub.slack.com/archives/C056AMWSFKJ) channel on [Slack](https://hackclub.com/slack/?event=onboard)
- [✅ ] I made this board from scratch, even if I followed a tutorial
- [✅ ] I have followed the directions in [README.md](https://github.com/hackclub/OnBoard/blob/main/README.md#getting-started)
  - [ ✅] Created a folder under `onboard/projects`
  - [ ✅] Filled out `TEMPLATE.md` as `README.md` inside your project folder
  - [✅ ] Uploaded `gerber.zip` and `schematic.pdf` inside your project folder
  - [✅ ] Created a folder called `src` and uploaded design files
  - [ ✅] Uploaded screenshot of PCB order called `cart.png` with all costs included
  - [ ✅] I am ordering the smallest batch size (ie. JLCPCB's smallest order is for 5 boards)
  - [Inapp. ] If outside the US I've checked that I can afford the customs charges in my country (which isn't covered by the grant)

- [✅ ] (Optional) This project is from a tutorial[^1].
- [ No] (Optional) I'm in a FIRST (FRC, FTC, FLL, etc.) team. The number is: ____

[^1]: Projects from a tutorial are 100% fine! We just want to ask so we can count how people are using tutorials.

2024-07-22 20:48 UTC, prophetorpheus commented
<!-- MY-ONBOARD-BOT --> Hi, I'm Orpheus Leap! Here to help you review your PR.
  
**projects/AvionicsPCB:**

Required files
||||
|---|---|---|
|✅| README.md | A description of your project |
|✅ | cart.png | ![cart.png](<https://raw.githubusercontent.com/hackclub/OnBoard/19a20a211cea8308f554c0ae017657c644d36911/projects/AvionicsPCB/cart.png>) |
|✅| gerber.zip | |
|✅ | [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/19a20a211cea8308f554c0ae017657c644d36911/projects/AvionicsPCB/schematic.pdf>) | Manually check [schematic.pdf](<https://raw.githubusercontent.com/hackclub/OnBoard/19a20a211cea8308f554c0ae017657c644d36911/projects/AvionicsPCB/schematic.pdf>) |
|✅| Source files - KiCAD | Found both PCB and SCH files |

You can view a render of your board over on [gerber.zip/2d](<https://gerber.zip/2d/?mode=layers&boardUrl=https://raw.githubusercontent.com/hackclub/OnBoard/19a20a211cea8308f554c0ae017657c644d36911/projects/AvionicsPCB/gerber.zip>)!
		
  Happy OnBoarding!
 <sub>This bot is a simpler helper for common submission types. If there's an error with this, please point it out and someone from the OnBoard team will look at it manually.</sub>

2024-07-24 19:38 UTC, LimesKey requested changes
Hi, I just wanted to confirm that the no assembly is intentional. If you're looking to assemble yourself, we allow you to purchase a stencil from JLCPCB.

2024-07-25 00:13 UTC, MelonMars commented
Hello, thanks for pointing out the no assembly. If I toggled that, it was unintentional. Where is that? Thanks!

2024-07-25 16:31 UTC, LimesKey commented
A guide to ordering from JLCPCB is [here](https://github.com/hackclub/OnBoard/blob/main/docs/ordering_from_JLCPCB.md), near the middle there is a section on Assembly and where the button is for that.

2024-07-25 18:30 UTC, MelonMars commented
I hadn't noticed that I did it wrong. Primarily due to shipping costs and whatnot it is becoming nigh impossible for me to reduce the price to below $100 (mainly due to shipping from JLCPCB, and just in general on, so I will be withdrawing my OnBoard Submission.

Carter

2024-07-25 18:30 UTC, closed without merging